# Generated by Django 5.0.7 on 2024-10-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answer_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-score', '-date']},
        ),
    ]
