# Generated by Django 5.1.2 on 2024-10-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("question", models.TextField()),
                ("author", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("score", models.IntegerField()),
            ],
        ),
    ]
