# Generated by Django 5.0.7 on 2024-10-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
