# Generated by Django 5.1.2 on 2024-10-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("about", models.TextField()),
                ("joined_on", models.DateField()),
                ("hobbies", models.TextField()),
                ("skills", models.TextField()),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("reputation", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("answers_posted", models.PositiveIntegerField(default=0)),
                ("questions_posted", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="questions",
        ),
    ]
